In [1]:
cobolfirst= """
IDENTIFICATION DIVISION.
PROGRAM-ID. SOMME.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 VAR-A PIC 9(5).
01 VAR-B PIC 9(5).
01 SUM PIC 9(6).
PROCEDURE DIVISION.
    MOVE 12345 TO VAR-A.
    MOVE 54321 TO VAR-B.
    ADD VAR-A, VAR-B GIVING SUM.
    DISPLAY 'La somme est : ' SUM.
    STOP RUN.
"""

In [2]:
code2 = """
IDENTIFICATION DIVISION.
PROGRAM-ID. GESTION-STOCK.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 PRODUIT.
   02 CODE-PRODUIT PIC X(10).
   02 QUANTITE PIC 9(5).
   02 PRIX UNITAIRE PIC 9(6)V99.
01 MONTANT-TOTAL PIC 9(8)V99 VALUE 0.
01 CHOIX-PRODUIT PIC X.

PROCEDURE DIVISION.
    DISPLAY "Gestion de stock de produits."
    PERFORM UNE-FOIS.
    PERFORM UNE-AUTRE-FOIS UNTIL CHOIX-PRODUIT = 'N'.
    DISPLAY "Fin du programme."
    STOP RUN.

UNE-FOIS.
    DISPLAY "Saisir le code du produit : "
    ACCEPT CODE-PRODUIT.
    DISPLAY "Saisir la quantité : "
    ACCEPT QUANTITE.
    DISPLAY "Saisir le prix unitaire : "
    ACCEPT PRIX-UNITAIRE.
    COMPUTE MONTANT-TOTAL = QUANTITE * PRIX-UNITAIRE.
    DISPLAY "Le montant total pour le produit ", CODE-PRODUIT, " est de ", MONTANT-TOTAL.
    DISPLAY "Voulez-vous saisir un autre produit (O/N) ? "
    ACCEPT CHOIX-PRODUIT.

UNE-AUTRE-FOIS.
    DISPLAY "Saisir le code du produit : "
    ACCEPT CODE-PRODUIT.
    DISPLAY "Saisir la quantité : "
    ACCEPT QUANTITE.
    DISPLAY "Saisir le prix unitaire : "
    ACCEPT PRIX-UNITAIRE.
    COMPUTE MONTANT-TOTAL = MONTANT-TOTAL + (QUANTITE * PRIX-UNITAIRE).
    DISPLAY "Le montant total pour le produit ", CODE-PRODUIT, " est de ", MONTANT-TOTAL.
    DISPLAY "Voulez-vous saisir un autre produit (O/N) ? "
    ACCEPT CHOIX-PRODUIT.

"""

In [3]:
code3 = """ 
IDENTIFICATION DIVISION.
PROGRAM-ID. VERIFICATION.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 NUMBER PIC 9(3).
01 RESULT PIC X(6).
PROCEDURE DIVISION.
    MOVE 123 TO NUMBER.
    IF NUMBER = 123 THEN
        MOVE 'CORRECT' TO RESULT
    ELSE
        MOVE 'INCORRECT' TO RESULT
    END-IF.
    DISPLAY 'Résultat : ' RESULT.
    STOP RUN. """

In [4]:
code = """
 code :

       ID DIVISION.
       PROGRAM-ID. EPSMLIST.
      *    THIS DEMONSTRATES CICS/DEBUG           - EPSDEMOS 2008
      *
      *    THIS PROGRAM WILL RECEIVE A DATE AND COVERT THE DATE TO
      *    AN INTEGER IN A CALLED PROGRAM TO DETERMINE DAYS FROM
      *    CURRENT DATE.
      *
      *    (C) 2008 IBM - JIM HILDNER RESERVED.
       ENVIRONMENT DIVISION.
       CONFIGURATION SECTION.
       SOURCE-COMPUTER. IBM-FLEX-ES.
       OBJECT-COMPUTER. IBM-FLEX-ES.
      *
       DATA DIVISION.
       WORKING-STORAGE SECTION.
      *
       01  W-FLAGS.
           10  W-SEND-FLAG                    PIC X.
               88  SEND-ERASE                   VALUE '1'.
               88  SEND-DATAONLY                VALUE '2'.
               88  SEND-MAPONLY                 VALUE '3'.
               88  SEND-DATAONLY-ALARM          VALUE '4'.

       01 W-CONVERSIONS.
           05  W-PMT-CNVRT     PIC X(12).
           05  W-PMT-NUMBER
               REDEFINES W-PMT-CNVRT
                               PIC 9(10)V99.
           05  WS-FORMAT-NUMBER PIC Z,ZZZ,ZZ9.99.
           05  W-PRINC-CNVRT   PIC X(12).
           05  W-PRINC-NUMBER
               REDEFINES W-PRINC-CNVRT
                               PIC 9(10)V99.

       01 W-CALL-PROGRAM                      PIC X(8).
       01 RESPONSE                            PIC S9(8) COMP.
       01 INTERNAL-PROGRAM-VARIABLES.
           05 RID-LENGTH                      PIC S9(9) COMP.
           05 DISP-COUNT                      PIC S9(4) COMP.
           05 MAX-LOOP                        PIC S9(4) COMP
                                              VALUE IS 8.
           05 END-OF-FILE                     PIC X.
           05 CLOSE-FILE                      PIC X.
      *
       01 W-RETIREMENT-WA                     PIC 9(4).
       01 W-COMAREA-LENGTH                    PIC 9(4) COMP.

       01 SAVE-COMM-AREA.
          COPY EPSMTCOM.

       01  END-OF-TRANS-MSG                 PIC X(30)
             VALUE 'END OF TRANSACTION - THANK YOU'.
           COPY DFHAID.
      *    COPY DFHEIBLK.

           COPY EPSMLIS.
       01  OUTMAP REDEFINES EPSMLISI.
           03 FILLER PIC X(110).
           03 OUTMAP-REPEATE OCCURS 8 TIMES.
              05 FILLER                    PIC X(5).
              05 OUTMAP-COMPANY            PIC X(24).
              05 FILLER                    PIC X(5).
              05 OUTMAP-PHONE-NUM          PIC X(13).
              05 FILLER                    PIC X(5).
              05 OUTMAP-RATE               PIC X(5).
              05 FILLER                    PIC X(5).
              05 OUTMAP-LOAN               PIC X(12).
              05 FILLER                    PIC X(5).
              05 OUTMAP-YEARS              PIC X(2).
           03 FILLER                       PIC X(5).
           03 OUTMAP-MSG                   PIC X(40).

           COPY EPSNBRPM.

           COPY EPSMORTF.

       01  W-COMMUNICATION-AREA.
           COPY EPSMTCOM.

       LINKAGE SECTION.

       01 DFHCOMMAREA.
       COPY EPSMTCOM.

       PROCEDURE DIVISION USING DFHCOMMAREA.

      * JPH - DO I need this for files
      * EXEC CICS HANDLE CONDITION H900-NOT-FOUND


       EPSCMORT-MAINLINE.
           MOVE LENGTH OF DFHCOMMAREA to W-COMAREA-LENGTH.
           MOVE DFHCOMMAREA           TO SAVE-COMM-AREA.
           EVALUATE TRUE
               WHEN EIBCALEN = ZERO
      * First time in - Show Screen
                   PERFORM A100-PROCESS-MAP
               WHEN EIBAID = DFHCLEAR
      * Process CLEAR key
                   EXEC CICS
                        RETURN
                   END-EXEC
               WHEN EIBAID = DFHPF3 OR DFHPF12
      * Process END/RETURN keys
                   EXEC CICS
                        RETURN
                   END-EXEC
               WHEN EIBAID = DFHENTER
      * Process ENTER Key
                   PERFORM A100-PROCESS-MAP
               WHEN OTHER
      * Present Invalid Key
                   PERFORM A100-PROCESS-MAP
           END-EVALUATE
           .
           MOVE SAVE-COMM-AREA TO DFHCOMMAREA.
           EXEC CICS RETURN END-EXEC.

       A100-PROCESS-MAP.

           PERFORM A310-ERASE-MAP.

           MOVE 0      TO RID-LENGTH.
           MOVE 'N'    TO CLOSE-FILE.
           MOVE 'N'    TO END-OF-FILE.

           EXEC CICS STARTBR DATASET('EPSMORTF')
                     RIDFLD(RID-LENGTH) RBA
                     EQUAL
                     RESP(RESPONSE) END-EXEC.

           IF (RESPONSE = DFHRESP(NORMAL))
              MOVE 'Y' TO CLOSE-FILE
              MOVE 1   TO DISP-COUNT
              PERFORM A150-PROCESS-FILE
                      UNTIL END-OF-FILE = 'Y'
                      OR    DISP-COUNT  > MAX-LOOP
           ELSE
              MOVE 'ERROR WITH START'         TO EPCMP1O
              MOVE RESPONSE                   TO EPLOAN1O
           END-IF
           .


           IF CLOSE-FILE = 'Y'
            EXEC CICS ENDBR FILE('EPSMORTF') END-EXEC
           END-IF
           .

           PERFORM A300-SEND-MAP.

       A150-PROCESS-FILE.

           EXEC CICS READNEXT FILE('EPSMORTF')
                    INTO(MORTGAGE-COMPANY-INFO)
                    RIDFLD(RID-LENGTH)
                    RBA RESP(RESPONSE)
           END-EXEC
           .
           IF (RESPONSE = DFHRESP(NORMAL))
              IF  EPSPCOM-PRINCIPLE-DATA OF SAVE-COMM-AREA
                                          < MORT-FILE-LOAN
              AND EPSPCOM-QUOTED-INTEREST-RATE OF SAVE-COMM-AREA
                                          > MORT-FILE-RATE
                 MOVE MORT-FILE-COMPANY
                                       TO OUTMAP-COMPANY(DISP-COUNT)
                 MOVE MORT-FILE-PHONE-NUM
                                       TO OUTMAP-PHONE-NUM(DISP-COUNT)
                 PERFORM A600-CALCULATE-MORTGAGE
                 MOVE MORT-FILE-RATE
                                       TO WS-FORMAT-NUMBER
                 MOVE WS-FORMAT-NUMBER(7:5)
                                       TO OUTMAP-RATE(DISP-COUNT)
                 MOVE EPSPCOM-RETURN-MONTH-PAYMENT OF DFHCOMMAREA
                                       TO WS-FORMAT-NUMBER
                 MOVE WS-FORMAT-NUMBER TO OUTMAP-LOAN(DISP-COUNT)
                 MOVE MORT-FILE-YEARS
                                       TO OUTMAP-YEARS(DISP-COUNT)
                 ADD 1                 TO DISP-COUNT
              END-IF
           ELSE
              IF (RESPONSE NOT = DFHRESP(ENDFILE))
                 MOVE 'ERROR WITH READ NEXT' TO EPCMP1O
                 MOVE RESPONSE               TO EPLOAN1O
              ELSE
                 MOVE 'Y' TO END-OF-FILE
              END-IF
           END-IF
           .

       A300-SEND-MAP.
                   EXEC CICS
                     SEND MAP ('EPSMLIS')
                         MAPSET('EPSMLIS')
                         FROM(EPSMLISO)
                   END-EXEC.

       A310-ERASE-MAP.
            MOVE LOW-VALUES TO EPSMLISO.
            EXEC CICS
                SEND MAP ('EPSMLIS')
                     MAPSET('EPSMLIS')
                     FROM(EPSMLISO)
                     ERASE
            END-EXEC.


       A600-CALCULATE-MORTGAGE.
           MOVE SAVE-COMM-AREA   TO DFHCOMMAREA.
           MOVE 'Y' TO EPSPCOM-YEAR-MONTH-IND
                                 OF DFHCOMMAREA.
           MOVE MORT-FILE-RATE   TO EPSPCOM-QUOTED-INTEREST-RATE
                                 OF DFHCOMMAREA.
           MOVE MORT-FILE-YEARS  TO EPSPCOM-NUMBER-OF-YEARS
                                 OF DFHCOMMAREA.
           MOVE 'EPSCSMRT' TO W-CALL-PROGRAM
           EXEC CICS LINK PROGRAM( W-CALL-PROGRAM )
                          COMMAREA( DFHCOMMAREA )
           END-EXEC
           MOVE EPSPCOM-RETURN-MONTH-PAYMENT
                                 OF DFHCOMMAREA
                                 TO WS-FORMAT-NUMBER.
           MOVE WS-FORMAT-NUMBER TO OUTMAP-LOAN(DISP-COUNT).


"""

In [5]:
code4 = """       
       ID DIVISION.
       PROGRAM-ID. EPSMLIST.
      *    THIS DEMONSTRATES CICS/DEBUG           - EPSDEMOS 2008
      *
      *    THIS PROGRAM WILL RECEIVE A DATE AND COVERT THE DATE TO
      *    AN INTEGER IN A CALLED PROGRAM TO DETERMINE DAYS FROM
      *    CURRENT DATE.
      *
      *    (C) 2008 IBM - JIM HILDNER RESERVED.
       ENVIRONMENT DIVISION.
       CONFIGURATION SECTION.
       SOURCE-COMPUTER. IBM-FLEX-ES.
       OBJECT-COMPUTER. IBM-FLEX-ES.
      *
       DATA DIVISION.
       WORKING-STORAGE SECTION.
      *
       01  W-FLAGS.
           10  W-SEND-FLAG                    PIC X.
               88  SEND-ERASE                   VALUE '1'.
               88  SEND-DATAONLY                VALUE '2'.
               88  SEND-MAPONLY                 VALUE '3'.
               88  SEND-DATAONLY-ALARM          VALUE '4'.

       01 W-CONVERSIONS.
           05  W-PMT-CNVRT     PIC X(12).
           05  W-PMT-NUMBER
               REDEFINES W-PMT-CNVRT
                               PIC 9(10)V99.
           05  WS-FORMAT-NUMBER PIC Z,ZZZ,ZZ9.99.
           05  W-PRINC-CNVRT   PIC X(12).
           05  W-PRINC-NUMBER
               REDEFINES W-PRINC-CNVRT
                               PIC 9(10)V99.

       01 W-CALL-PROGRAM                      PIC X(8).
       01 RESPONSE                            PIC S9(8) COMP.
       01 INTERNAL-PROGRAM-VARIABLES.
           05 RID-LENGTH                      PIC S9(9) COMP.
           05 DISP-COUNT                      PIC S9(4) COMP.
           05 MAX-LOOP                        PIC S9(4) COMP
                                              VALUE IS 8.
           05 END-OF-FILE                     PIC X.
           05 CLOSE-FILE                      PIC X.
      *
       01 W-RETIREMENT-WA                     PIC 9(4).
       01 W-COMAREA-LENGTH                    PIC 9(4) COMP.

       01 SAVE-COMM-AREA.
          COPY EPSMTCOM.

       01  END-OF-TRANS-MSG                 PIC X(30)
             VALUE 'END OF TRANSACTION - THANK YOU'.
           COPY DFHAID.
      *    COPY DFHEIBLK.

           COPY EPSMLIS.
       01  OUTMAP REDEFINES EPSMLISI.
           03 FILLER PIC X(110).
           03 OUTMAP-REPEATE OCCURS 8 TIMES.
              05 FILLER                    PIC X(5).
              05 OUTMAP-COMPANY            PIC X(24).
              05 FILLER                    PIC X(5).
              05 OUTMAP-PHONE-NUM          PIC X(13).
              05 FILLER                    PIC X(5).
              05 OUTMAP-RATE               PIC X(5).
              05 FILLER                    PIC X(5).
              05 OUTMAP-LOAN               PIC X(12).
              05 FILLER                    PIC X(5).
              05 OUTMAP-YEARS              PIC X(2).
           03 FILLER                       PIC X(5).
           03 OUTMAP-MSG                   PIC X(40).

           COPY EPSNBRPM.

           COPY EPSMORTF.

       01  W-COMMUNICATION-AREA.
           COPY EPSMTCOM.

       LINKAGE SECTION.

       01 DFHCOMMAREA.
       COPY EPSMTCOM.

       PROCEDURE DIVISION USING DFHCOMMAREA.

      * JPH - DO I need this for files
      * EXEC CICS HANDLE CONDITION H900-NOT-FOUND


       EPSCMORT-MAINLINE.
           MOVE LENGTH OF DFHCOMMAREA to W-COMAREA-LENGTH.
           MOVE DFHCOMMAREA           TO SAVE-COMM-AREA.
           EVALUATE TRUE
               WHEN EIBCALEN = ZERO
      * First time in - Show Screen
                   PERFORM A100-PROCESS-MAP
               WHEN EIBAID = DFHCLEAR
      * Process CLEAR key
                   EXEC CICS
                        RETURN
                   END-EXEC
               WHEN EIBAID = DFHPF3 OR DFHPF12
      * Process END/RETURN keys
                   EXEC CICS
                        RETURN
                   END-EXEC
               WHEN EIBAID = DFHENTER
      * Process ENTER Key
                   PERFORM A100-PROCESS-MAP
               WHEN OTHER
      * Present Invalid Key
                   PERFORM A100-PROCESS-MAP
           END-EVALUATE
           .
           MOVE SAVE-COMM-AREA TO DFHCOMMAREA.
           EXEC CICS RETURN END-EXEC.

       A100-PROCESS-MAP.

           PERFORM A310-ERASE-MAP.

           MOVE 0      TO RID-LENGTH.
           MOVE 'N'    TO CLOSE-FILE.
           MOVE 'N'    TO END-OF-FILE.

           EXEC CICS STARTBR DATASET('EPSMORTF')
                     RIDFLD(RID-LENGTH) RBA
                     EQUAL
                     RESP(RESPONSE) END-EXEC.

           IF (RESPONSE = DFHRESP(NORMAL))
              MOVE 'Y' TO CLOSE-FILE
              MOVE 1   TO DISP-COUNT
              PERFORM A150-PROCESS-FILE
                      UNTIL END-OF-FILE = 'Y'
                      OR    DISP-COUNT  > MAX-LOOP
           ELSE
              MOVE 'ERROR WITH START'         TO EPCMP1O
              MOVE RESPONSE                   TO EPLOAN1O
           END-IF
           .


           IF CLOSE-FILE = 'Y'
            EXEC CICS ENDBR FILE('EPSMORTF') END-EXEC
           END-IF
           .

           PERFORM A300-SEND-MAP.

       A150-PROCESS-FILE.

           EXEC CICS READNEXT FILE('EPSMORTF')
                    INTO(MORTGAGE-COMPANY-INFO)
                    RIDFLD(RID-LENGTH)
                    RBA RESP(RESPONSE)
           END-EXEC
           .
           IF (RESPONSE = DFHRESP(NORMAL))
              IF  EPSPCOM-PRINCIPLE-DATA OF SAVE-COMM-AREA
                                          < MORT-FILE-LOAN
              AND EPSPCOM-QUOTED-INTEREST-RATE OF SAVE-COMM-AREA
                                          > MORT-FILE-RATE
                 MOVE MORT-FILE-COMPANY
                                       TO OUTMAP-COMPANY(DISP-COUNT)
                 MOVE MORT-FILE-PHONE-NUM
                                       TO OUTMAP-PHONE-NUM(DISP-COUNT)
                 PERFORM A600-CALCULATE-MORTGAGE
                 MOVE MORT-FILE-RATE
                                       TO WS-FORMAT-NUMBER
                 MOVE WS-FORMAT-NUMBER(7:5)
                                       TO OUTMAP-RATE(DISP-COUNT)
                 MOVE EPSPCOM-RETURN-MONTH-PAYMENT OF DFHCOMMAREA
                                       TO WS-FORMAT-NUMBER
                 MOVE WS-FORMAT-NUMBER TO OUTMAP-LOAN(DISP-COUNT)
                 MOVE MORT-FILE-YEARS
                                       TO OUTMAP-YEARS(DISP-COUNT)
                 ADD 1                 TO DISP-COUNT
              END-IF
           ELSE
              IF (RESPONSE NOT = DFHRESP(ENDFILE))
                 MOVE 'ERROR WITH READ NEXT' TO EPCMP1O
                 MOVE RESPONSE               TO EPLOAN1O
              ELSE
                 MOVE 'Y' TO END-OF-FILE
              END-IF
           END-IF
           .

       A300-SEND-MAP.
                   EXEC CICS
                     SEND MAP ('EPSMLIS')
                         MAPSET('EPSMLIS')
                         FROM(EPSMLISO)
                   END-EXEC.

       A310-ERASE-MAP.
            MOVE LOW-VALUES TO EPSMLISO.
            EXEC CICS
                SEND MAP ('EPSMLIS')
                     MAPSET('EPSMLIS')
                     FROM(EPSMLISO)
                     ERASE
            END-EXEC.


       A600-CALCULATE-MORTGAGE.
           MOVE SAVE-COMM-AREA   TO DFHCOMMAREA.
           MOVE 'Y' TO EPSPCOM-YEAR-MONTH-IND
                                 OF DFHCOMMAREA.
           MOVE MORT-FILE-RATE   TO EPSPCOM-QUOTED-INTEREST-RATE
                                 OF DFHCOMMAREA.
           MOVE MORT-FILE-YEARS  TO EPSPCOM-NUMBER-OF-YEARS
                                 OF DFHCOMMAREA.
           MOVE 'EPSCSMRT' TO W-CALL-PROGRAM
           EXEC CICS LINK PROGRAM( W-CALL-PROGRAM )
                          COMMAREA( DFHCOMMAREA )
           END-EXEC
           MOVE EPSPCOM-RETURN-MONTH-PAYMENT
                                 OF DFHCOMMAREA
                                 TO WS-FORMAT-NUMBER.
           MOVE WS-FORMAT-NUMBER TO OUTMAP-LOAN(DISP-COUNT).

"""

In [32]:
import sys

print(sys.version)


3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]


In [33]:
pip show streamlit

Name: streamlit
Version: 1.24.0
Summary: A faster way to build and share data apps
Home-page: https://streamlit.io
Author: Snowflake Inc
Author-email: hello@streamlit.io
License: Apache License 2.0
Location: c:\users\pc\onedrive\bureau\ange'ecc files\documents\mobilite\cesure\gounadon_ange-marie\deepblock\cobol\.venv\lib\site-packages
Requires: altair, blinker, cachetools, click, gitpython, importlib-metadata, numpy, packaging, pandas, pillow, protobuf, pyarrow, pydeck, pympler, python-dateutil, requests, rich, tenacity, toml, tornado, typing-extensions, tzlocal, validators, watchdog
Required-by: 
Note: you may need to restart the kernel to use updated packages.


In [26]:
pip show langchain

Name: langchain
Version: 0.0.239
Summary: Building applications with LLMs through composability
Home-page: https://www.github.com/hwchase17/langchain
Author: 
Author-email: 
License: MIT
Location: c:\users\pc\onedrive\bureau\ange'ecc files\documents\mobilite\cesure\gounadon_ange-marie\deepblock\cobol\.venv\lib\site-packages
Requires: aiohttp, async-timeout, dataclasses-json, langsmith, numexpr, numpy, openapi-schema-pydantic, pydantic, PyYAML, requests, SQLAlchemy, tenacity
Required-by: 
Note: you may need to restart the kernel to use updated packages.


In [25]:
pip show CTransformers

Name: ctransformers
Version: 0.2.14
Summary: Python bindings for the Transformer models implemented in C/C++ using GGML library.
Home-page: https://github.com/marella/ctransformers
Author: Ravindra Marella
Author-email: mv.ravindra007@gmail.com
License: MIT
Location: c:\users\pc\onedrive\bureau\ange'ecc files\documents\mobilite\cesure\gounadon_ange-marie\deepblock\cobol\.venv\lib\site-packages
Requires: huggingface-hub
Required-by: 
Note: you may need to restart the kernel to use updated packages.


In [ ]:
pip install --upgrade langchain

In [10]:
pip install sentencepiece

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.1.2 -> 23.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [15]:
pip install sentence_transformers


                                              0.0/86.0 kB ? eta -:--:--
     ----                                     10.2/86.0 kB ? eta -:--:--
     ----                                     10.2/86.0 kB ? eta -:--:--
     ----                                     10.2/86.0 kB ? eta -:--:--
     ----                                     10.2/86.0 kB ? eta -:--:--
     ----                                     10.2/86.0 kB ? eta -:--:--
     ----                                     10.2/86.0 kB ? eta -:--:--
     -------------                           30.7/86.0 kB 77.0 kB/s eta 0:00:01
     -------------                           30.7/86.0 kB 77.0 kB/s eta 0:00:01
     -------------                           30.7/86.0 kB 77.0 kB/s eta 0:00:01
     -------------                           30.7/86.0 kB 77.0 kB/s eta 0:00:01
     -------------                           30.7/86.0 kB 77.0 kB/s eta 0:00:01
     -------------                           30.7/86.0 kB 77.0 kB/s eta 0:00:01
     ----


[notice] A new release of pip is available: 23.1.2 -> 23.2
[notice] To update, run: python.exe -m pip install --upgrade pip


     -----                                    1.3/9.3 MB 59.3 kB/s eta 0:02:16
     -----                                    1.3/9.3 MB 59.0 kB/s eta 0:02:16
     -----                                    1.3/9.3 MB 59.0 kB/s eta 0:02:16
     -----                                    1.3/9.3 MB 59.0 kB/s eta 0:02:16
     -----                                    1.3/9.3 MB 59.0 kB/s eta 0:02:16
     -----                                    1.3/9.3 MB 59.0 kB/s eta 0:02:16
     -----                                    1.3/9.3 MB 59.0 kB/s eta 0:02:16
     -----                                    1.3/9.3 MB 59.0 kB/s eta 0:02:16
     -----                                    1.3/9.3 MB 59.0 kB/s eta 0:02:16
     -----                                    1.3/9.3 MB 59.2 kB/s eta 0:02:15
     -----                                    1.3/9.3 MB 59.2 kB/s eta 0:02:15
     -----                                    1.3/9.3 MB 59.2 kB/s eta 0:02:15
     -----                                    1.3/9.

In [16]:
pip install faiss-cpu


[notice] A new release of pip is available: 23.1.2 -> 23.2
[notice] To update, run: python.exe -m pip install --upgrade pip



                                              0.0/10.8 MB ? eta -:--:--
                                              0.0/10.8 MB 1.4 MB/s eta 0:00:08
                                              0.1/10.8 MB 1.7 MB/s eta 0:00:07
     -                                        0.3/10.8 MB 2.7 MB/s eta 0:00:04
     -                                        0.3/10.8 MB 2.9 MB/s eta 0:00:04
     -                                        0.5/10.8 MB 2.6 MB/s eta 0:00:04
     --                                       0.6/10.8 MB 2.8 MB/s eta 0:00:04
     --                                       0.7/10.8 MB 2.8 MB/s eta 0:00:04
     ---                                      0.9/10.8 MB 3.0 MB/s eta 0:00:04
     ---                                      1.0/10.8 MB 3.0 MB/s eta 0:00:04
     ----                                     1.2/10.8 MB 3.1 MB/s eta 0:00:04
     -----                                    1.4/10.8 MB 3.1 MB/s eta 0:00:04
     -----                                    1.5/10.8 MB 

In [2]:
from langchain.vectorstores import FAISS
from langchain.text_splitter import CharacterTextSplitter
from langchain.embeddings import HuggingFaceEmbeddings
"""
# Load PDF file from data path
loader = DirectoryLoader('data/',
                         glob="*.pdf",
                         loader_cls=PyPDFLoader)
documents = loader.load()
"""
# Split text from PDF into chunks

'\n# Load PDF file from data path\nloader = DirectoryLoader(\'data/\',\n                         glob="*.pdf",\n                         loader_cls=PyPDFLoader)\ndocuments = loader.load()\n'

In [3]:
def split_code(code, chunk_size=500,  chunk_overlap=50):
    splitter = CharacterTextSplitter(chunk_size=chunk_size, chunk_overlap=chunk_overlap)
    chunks = splitter.split_text(code)
    return chunks

In [4]:
chunks = split_code(code, chunk_size=500,  chunk_overlap=50)

Created a chunk of size 847, which is longer than the specified 500
Created a chunk of size 629, which is longer than the specified 500
Created a chunk of size 780, which is longer than the specified 500
Created a chunk of size 930, which is longer than the specified 500
Created a chunk of size 1629, which is longer than the specified 500
Created a chunk of size 774, which is longer than the specified 500


In [5]:
print(len(chunks))
print(chunks)

14
['code :', "ID DIVISION.\n       PROGRAM-ID. EPSMLIST.\n      *    THIS DEMONSTRATES CICS/DEBUG           - EPSDEMOS 2008\n      *\n      *    THIS PROGRAM WILL RECEIVE A DATE AND COVERT THE DATE TO\n      *    AN INTEGER IN A CALLED PROGRAM TO DETERMINE DAYS FROM\n      *    CURRENT DATE.\n      *\n      *    (C) 2008 IBM - JIM HILDNER RESERVED.\n       ENVIRONMENT DIVISION.\n       CONFIGURATION SECTION.\n       SOURCE-COMPUTER. IBM-FLEX-ES.\n       OBJECT-COMPUTER. IBM-FLEX-ES.\n      *\n       DATA DIVISION.\n       WORKING-STORAGE SECTION.\n      *\n       01  W-FLAGS.\n           10  W-SEND-FLAG                    PIC X.\n               88  SEND-ERASE                   VALUE '1'.\n               88  SEND-DATAONLY                VALUE '2'.\n               88  SEND-MAPONLY                 VALUE '3'.\n               88  SEND-DATAONLY-ALARM          VALUE '4'.", '01 W-CONVERSIONS.\n           05  W-PMT-CNVRT     PIC X(12).\n           05  W-PMT-NUMBER\n               REDEFINES W-P

In [6]:
# Load embeddings model


#sentence-transformers/all-MiniLM-L6-v2
#sentence-transformers/all-mpnet-base-v2
#sentence-transformers/all-distilroberta-v1
#   'Salesforce/codet5-small'


embeddings = HuggingFaceEmbeddings(model_name='sentence-transformers/all-MiniLM-L6-v2',
                                   model_kwargs={'device': 'cpu'})

c:\Users\pc\OneDrive\Bureau\Ange'ECC files\DOCUMENTS\Mobilite\Cesure\GOUNADON_Ange-Marie\DeepBlock\COBOL\.venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [7]:
# Build and persist FAISS vector store
vectorstore = FAISS.from_texts(chunks, embeddings)
vectorstore.save_local('vectorstore/db_faiss')

In [19]:
code_template = """Analyze the COBOL code to provide a relevant explanation.
If you don't know the answer, just say that you don't know, don't try to make up an answer.
- code
```COBOL
{code_cobol}
```
Only return the explanation of the code above and nothing else.
- Explanation of the above code:
"""

In [18]:
# File: llm.py
from langchain.llms import CTransformers

# Local CTransformers wrapper for Llama-2-7B-Chat
path = r"C:/Users/pc/OneDrive/Bureau/Ange'ECC files/DOCUMENTS/Mobilite/Cesure/GOUNADON_Ange-Marie/DeepBlock/IA_generative/.venv39/bin/llama-2-13b-chat.ggmlv3.q4_0.bin"
llm = CTransformers(model=path, # Location of downloaded GGML model
                    model_type='llama', # Model type Llama
                    config={'max_new_tokens': 256,
                            'temperature': 0.01})

c:\Users\pc\OneDrive\Bureau\Ange'ECC files\DOCUMENTS\Mobilite\Cesure\GOUNADON_Ange-Marie\DeepBlock\COBOL\.venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [9]:
#from langchain.llms import LlamaCpp
#from langchain.chains import RetrievalQA


from langchain import PromptTemplate
from langchain.chains import LLMChain
from langchain.embeddings import HuggingFaceEmbeddings
from langchain.vectorstores import FAISS

In [37]:
# Wrap prompt template in a PromptTemplate object
def set_prompt():
    prompt = PromptTemplate(template=code_template,
                            input_variables=['code_cobol'])
    return prompt


# Build RetrievalQA object
def build_cobol_mean(llm, prompt, vectordb):
    chain = LLMChain(llm=llm,
                    prompt=PromptTemplate.from_template(code_template)),
    return chain


# Instantiate QA object
def setup_mean():
    embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2",
                                       model_kwargs={'device': 'cpu'})
    chemin = r"C:/Users/pc/OneDrive/Bureau/Ange'ECC files/DOCUMENTS/Mobilite/Cesure/GOUNADON_Ange-Marie/DeepBlock/COBOL/vectorstore/db_faiss"
    vectordb = FAISS.load_local(chemin, embeddings)
    prompt = set_prompt()
    answer = build_cobol_mean(llm, prompt, vectordb)

    return answer

In [38]:
# File: main.py
import argparse
import timeit

if __name__ == "__main__":
    answer = setup_mean()
    

In [41]:
answer

(LLMChain(memory=None, callbacks=None, callback_manager=None, verbose=False, tags=None, metadata=None, prompt=PromptTemplate(input_variables=['code_cobol'], output_parser=None, partial_variables={}, template="Analyze the COBOL code to provide a relevant explanation.\nIf you don't know the answer, just say that you don't know, don't try to make up an answer.\n- code\n```COBOL\n{code_cobol}\n```\nOnly return the explanation of the code above and nothing else.\n- Explanation of the above code:\n", template_format='f-string', validate_template=True), llm=CTransformers(cache=None, verbose=False, callbacks=None, callback_manager=None, tags=None, metadata=None, client=<ctransformers.llm.LLM object at 0x0000021100C89E80>, model="C:/Users/pc/OneDrive/Bureau/Ange'ECC files/DOCUMENTS/Mobilite/Cesure/GOUNADON_Ange-Marie/DeepBlock/IA_generative/.venv39/bin/llama-2-13b-chat.ggmlv3.q4_0.bin", model_type='llama', model_file=None, config={'max_new_tokens': 256, 'temperature': 0.01}, lib=None), output_k

In [52]:
from langchain.prompts.chat import (
    ChatPromptTemplate,
    HumanMessagePromptTemplate,
)
human_message_prompt = HumanMessagePromptTemplate(
        prompt=PromptTemplate(
            template=code_template,
            input_variables=["code_cobol"],
        )
    )

#path=r"C:/Users/pc/OneDrive/Bureau/Ange'ECC files/DOCUMENTS/Mobilite/Cesure/GOUNADON_Ange-Marie/DeepBlock/IA_generative/.venv39/bin/llama-2-13b-chat.ggmlv3.q4_0.bin"
#llm = LlamaCpp(model_path=path)
chat_prompt_template = ChatPromptTemplate.from_messages([human_message_prompt])
chain = LLMChain(llm=llm, prompt=chat_prompt_template)
print(chain.run(code))

```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
     
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
     
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
     
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```



In [57]:
template3 = """
- code
```COBOL
{code_cobol}
```
- Explanation of the above code \n
"""
prompt = PromptTemplate.from_template(template3)
formatted_prompt = prompt.format(code_cobol=code)
res = llm(prompt= formatted_prompt, llm= llm)
print(res)

       ID DIV.
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
       ID DIV.
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
       ID DIV.
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
       ID DIV.
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```



In [66]:
from langchain.prompts import PromptTemplate

prompt=PromptTemplate(
            template=code_template,
            input_variables=["code_cobol"])
chain2 = LLMChain(llm=llm, prompt=prompt)
print(chain2.run(code))

This COBased on this program to convert date conversion from the code written in this is a COBrie
      
     
The code that converts date conversion of the code
This COBased on the code
This COBased on the code
```
This COBased on the code
This COBased on the code
This program to convert date conversion from the code written in this is a COBrie
      
     
The code that converts date conversion of the code
This COBased on the code
This COBased on the code
```
This COBased on the code
This COBased on the code
This program to convert date conversion from the code written in this is a COBrie
      
     
The above code that converts date conversion of the code
This COBased on the code
This COBased on the code
```
This COBased on the code
This COBased on the code
This program to convert date conversion from the code written in this is a COBrie
      
     
The code that converts date conversion of the code
This COBased on the code
This COBased on the code
```
This CO


In [7]:
from langchain.prompts import PromptTemplate
from langchain.chains import LLMChain

template3 = """
- code
```COBOL
{code_cobol}
```
- Explanation of the above code \n
"""

prompt=PromptTemplate(
            template=template3,
            input_variables=["code_cobol"])
chain3 = LLMChain(llm=llm, prompt=prompt)
print(chain3.run(code))

       ID DIV.
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
       ID DIV.
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
       ID DIV.
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
       ID DIV.
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```



In [65]:
from langchain.prompts import PromptTemplate
template="Qui est {nom}?"
prompt=PromptTemplate(
            template=template,
            input_variables=["nom"])

chain_ = LLMChain(llm=llm, prompt=prompt)

print(chain_.run("Barack Obama"))


Barack Obama is the 44th President of the United States. He was born on August 4, 1961, in Honolulu, Hawaii, to a white mother and a black father from Kenya. Obama grew up in Chicago, Illinois, and graduated from Columbia University and Harvard Law School. Before his political career, he worked as a community organizer and civil rights attorney.

Obama was first elected to the U.S. Senate in 2004, representing Illinois. In 2008, he won the Democratic presidential nomination and went on to defeat Republican candidate John McCain in the general election, becoming the first African American to be elected President of the United States.

During his presidency, Obama signed several landmark pieces of legislation, including the Affordable Care Act (ACA), which expanded healthcare coverage to millions of Americans, and the Dodd-Frank Wall Street Reform and Consumer Protection Act, which aimed to regulate the financial industry and prevent future economic crises. He also ended the war in Iraq

In [65]:
from langchain.prompts import PromptTemplate
from langchain.chains import LLMChain
from langchain.llms import CTransformers
from langchain.llms import LlamaCpp


#llm = CTransformers(model=path, model_type='llama',
#                        config={'max_new_tokens': 256, 'temperature': 0.01})


In [2]:
template="""Given the description below, find the best matching element.\n
Description : {description}
Matching:
"""

prompt=PromptTemplate(
            template=template,
            input_variables=["description"])


chain_ = LLMChain(llm=llm, prompt=prompt)
des = "j'ai un cousin qui se marie demain. Il est passionné de voyages et football. Quel est le meilleur cadeau de mariage pour lui?"
print("Ci-dessous une ou plusieurs idées:")
print(chain_.run(des))

A) Un voyage en avion
B) Un ballon de football
C) Une photo de son équipe favorite de football
D) Un livre de voyages
E) Un abonnement à un site de voyages
Please select the best matching element.


In [6]:

template=""""Étant donné la description ci-dessous, trouvez le meilleur élément correspondant. Fournissez trois propositions de réponse au plus."\n
Description : {description}
Réponse: Raisonnons étape par étape.
"""

prompt=PromptTemplate(
            template=template,
            input_variables=["description"])


chain_ = LLMChain(llm=llm, prompt=prompt)
des = "Je suis un ado de 17ans. Je suis très rapide et élancé. Quel est le meilleur sport pour moi?"
print("Ci-dessous une ou plusieurs idées:")
print(chain_.run(des))

Ci-dessous une ou plusieurs idées:

Proposition 1: "Si vous êtes très rapide et élancé, je recommande fortement que vous essayiez le football. Le football est un sport qui nécessite une grande vitesse et une bonne condition physique pour courir sur le terrain."
Proposition 2: "Si vous êtes très rapide et élancé, vous devriez également envisager la natation. La natation est un sport qui nécessite une grande vitesse et une bonne condition physique pour nager dans l'eau."
Proposition 3: "Si vous êtes très rapide et élancé, je recommande fortement que vous essayiez le tennis. Le tennis est un sport qui nécessite une grande vitesse et une bonne condition physique pour courir sur le terrain et frapper des balles."


In [52]:
template_ = """Je veux que vous agissiez en tant que conseiller en fournissant des 
conseils sur divers sujets. Suggérez la meilleur réponse qui correspond à la description ci-dessous! 
description - « {description} »
Réponse:
"""


prompt=PromptTemplate(
            template=template_,
            input_variables=["description"])


chain_ = LLMChain(llm=llm, prompt=prompt)
des = "Je suis un ado de 17ans. Je suis très rapide et grand de taille. Quel est le meilleur sport pour moi?"
print("Ci-dessous une ou plusieurs idées:")
print(chain_.run(des))

Ci-dessous une ou plusieurs idées:

Bonjour ! En tant que conseiller, je vous recommande fortement de pratiquer le basket-ball si vous êtes rapide et grand de taille. Le basket-ball est un sport qui met en avant la vitesse, l'agilité et la force physique, ce qui correspond parfaitement à vos qualités physiques.

En plus de cela, le basket-ball est un sport très populaire et compétitif, il y aura toujours des occasions de jouer et de vous mesurer aux autres joueurs. De plus, il y a une grande variété de positions dans un équipe de basket-ball, donc vous pourrez choisir celle qui correspond le mieux à vos compétences et à vos préférences.

En résumé, le basket-ball est un sport idéal pour un ado de 17 ans rapide et grand de taille comme vous, il offre une grande variété de positions et permet de développer votre vitesse, votre agilité et votre force physique.


In [53]:
des = "Donne les meilleurs cadeaux pour une jeune femme enceinte de 30 ans, avec un prix maximum de 500 euros"
print(chain_.run(des))

Bonjour! Pour une jeune femme enceinte de 30 ans, je vous suggest des cadeaux qui sont both fun and practical. Here are my top three gift ideas that fit within your budget of 500 euros:
1. A prenatal massage or spa day: Pregnancy can be a challenging time, both physically and emotionally. Treating your loved one to a relaxing spa day or prenatal massage can help ease her discomfort, reduce stress, and promote overall well-being. Many spas offer special packages for pregnant women, including customized massages and facials that are safe and nurturing.
2. A personalized journal or planner: As your loved one prepares for motherhood, a thoughtful gift like a personalized journal or planner can help her stay organized, track her progress, and document her pregnancy journey. You could even include a special message or quote inside the cover to make it extra special.
3. A cozy throw blanket or pillow: As her body changes during pregnancy, your loved one may find comfort in soft, cozy textiles

In [54]:
des_ = "j'ai un cousin qui se marie demain. Il est passionné de voyages et football. Quel est le meilleur cadeau de mariage pour lui?"
print("Ci-dessous une ou plusieurs idées:")
print(chain_.run(des_))

Ci-dessous une ou plusieurs idées:

Option 1 : Un voyage de rêve en Asie !
Option 2 : Des billets de football VIP pour une partie de l'équipe favorite de votre cousin !
Option 3 : Un pack de voyages avec des activités sportives et culturelles.


In [82]:
L_template = """ 
Vous agirez en tant qu'expert spécialisé dans la recherche et sélection d'objet et de service pour offrir des cadeaux.
Suggérez la meilleur réponse qui correspond à la description ci-dessous!
description - « {description} »
Réponse:
"""
"""llm = CTransformers(model=path, model_type='llama',
                        config={'max_new_tokens': 256, 'temperature': 0.01})
"""
llm = LlamaCpp(model_path=path, n_ctx=4096, max_tokens=256, verbose=True)



prompt=PromptTemplate(
            template=L_template,
            input_variables=["description"])


chain_ = LLMChain(llm=llm, prompt=prompt)
des = "Donne les meilleurs cadeaux pour une jeune femme enceinte de 30 ans, avec un prix maximum de 500 euros"
print("Ci-dessous une ou plusieurs idées:")
print(chain_.run(des))

AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 | 


Ci-dessous une ou plusieurs idées:
Bonjour! Pour une jeune femme enceinte de 30 ans, je vous suggère les cadeaux suivants :
1. Un bouquet de fleurs fraîches et délicieux pour elle à prendre soin d'elle et de son bébé.
2. Un abonnement mensuel sur une plateforme de streaming pour qu'elle puisse profiter de ses moments de repos et de divertissement pendant la grossesse.
3. Un booklet de self-soins pour elle, avec des produits de soins pour les mains, le visage et le corps, qui peuvent l'aider à se sentir bien et à prévenir les tensions et les douleurs liées à la grossesse.
4. Un massage prénatal pour elle, ce qui peut l'aider à se détendre et à réduire les tensions musculaires liées à la grossesse.
5. Un set de vêtements confortables et coquets pour elle, en coton ou en matériaux doux, qui peuvent l'aider à se sentir bien et à supporter le poids de son corps pendant


In [67]:

chain_ = LLMChain(llm=llm, prompt=prompt)
des_ = "Donne les meilleurs cadeaux pour un cousin qui se marie demain et qui est passionné de voyages et football"
print("Ci-dessous une ou plusieurs idées:")
print(chain_.run(des_))

Ci-dessous une ou plusieurs idées:


Llama.generate: prefix-match hit


Merci d'avance!


Note: Les réponses doivent être personnalisées et originales, car votre expertise est la clé pour donner une belle expérience aux clients.


In [68]:
chain_ = LLMChain(llm=llm, prompt=prompt)

des2 = "Donne les meilleurs sport pour un ado de 17ans. Il est suis très rapide et grand de taille."
print("Ci-dessous une ou plusieurs idées:")
print(chain_.run(des2))

Ci-dessous une ou plusieurs idées:


Llama.generate: prefix-match hit


In [69]:
chain_ = LLMChain(llm=llm, prompt=prompt)

desx = "Je suis un ado de 17ans. Je suis très rapide et grand de taille. Quel est le meilleur sport pour moi?"
print("Ci-dessous une ou plusieurs idées:")
print(chain_.run(desx))

Ci-dessous une ou plusieurs idées:


Llama.generate: prefix-match hit



Essayez de répondre en utilisant des mots techniques pertinents et des termes professionnels pertinents dans votre domaine d'expertise.




Vous pouvez utiliser les informations suivantes pour votre réponse :

* Le sport doit être praticable avec une taille de 1,90m et un poids de 85kg.
* L'objectif est de trouver un sport qui permet de développer des compétences physiques et mentales solides.
* Le sport doit être passionnant et intéressant pour vous.


In [70]:
formatted_prompt = prompt.format(description=des)
res = llm(prompt= formatted_prompt, llm= llm)
print(res)

Llama.generate: prefix-match hit


##COBOL

In [20]:
from langchain.llms import LlamaCpp
from langchain.chains import LLMChain
from langchain.prompts import PromptTemplate
from langchain.callbacks.manager import CallbackManager
from langchain.callbacks.streaming_stdout import StreamingStdOutCallbackHandler

callback_manager = CallbackManager([StreamingStdOutCallbackHandler()])
path=r"C:/Users/pc/OneDrive/Bureau/Ange'ECC files/DOCUMENTS/Mobilite/Cesure/GOUNADON_Ange-Marie/DeepBlock/IA_generative/.venv39/bin/llama-2-13b-chat.ggmlv3.q4_0.bin"


In [21]:
llm = LlamaCpp(model_path=path, n_ctx=4096, max_tokens=512, callback_manager=callback_manager, verbose=True)
#Girst : max_tokens=512
#2s
#https://api.python.langchain.com/en/latest/llms/langchain.llms.llamacpp.LlamaCpp.html

AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 | 


In [8]:
template_x = """
- code
```COBOL
{code_cobol}
```
- Explanation of the above code \n
"""

prompt_x=PromptTemplate(
            template=template_x,
            input_variables=["code_cobol"])
chain_x = LLMChain(llm=llm, prompt=prompt_x)
print(chain_x.run(code))

the above code is written in COBOL programming language. it's a sample code for demonstrating CICS debug. this program will receive a date and convert it to an integer value, which will then be used to determine the number of days from the current date. the program uses the EPSMLIS and EPSMORTF areas to store data temporarily while processing the map.
The code starts with an ID division, which specifies the program name and version. the next section is the configuration division, where the environment variables are defined. these include RID length, DISP count, and maximum loop number. the W-RETIREMENT-WA variable is also defined in this section, which is used to store the return value from the CICS program.
the next section is the data division, where the working storage section is defined. this includes variables such as W-FLAGS, W-PMT-CNVRT, and W-PRINC-CNVRT, which are used to store flags and conversion values. the OUTMAP-REPEATE variable is also defined in this section, which stor

Second : 24m12.8s -- 30mins de mémoire pour first

First : The COBOL program above is designed to handle the mortgage loan processing, specifically for the monthly interest rate calculation. Here's a breakdown of the code:
1. Data Division: The first section declares various data items used throughout the program, such as flags, conversion tables, and external variable lengths.
2. Configuration Section: This section defines the environment variables for the program, including the source and object computer names, working storage size, and other configuration parameters.
3. Program ID: The program ID is declared here, along with the version number.
4. PROCEDURE DIVISION: The procedure division is where the actual program logic is contained. It consists of several sections:
a. Evaluate True/False: This section evaluates a series of conditions and branches to different sections based on the results. For example, it checks if the EIBCALEN (a condition code) is zero, and if so, it branches to the A100-PROCESS-MAP section.
b. Process Map: This section performs the actual mortgage loan processing. It reads the next record from the file, evaluates the record, and updates the appropriate fields in the OUTMAP structure. If any errors occur during the processing, the program branches to the A310-ERASE-MAP section to reset the map.
c. Send Map: This section sends the updated OUTMAP structure to the CICS server for further processing.
5. LINKAGE SECTION: The linkage section defines the external references used by the program, such as the EPSMLIST and EPSMTCOM libraries.
6. PROCEDURE DIVISION USING SAVE-COMM-AREA: This section is similar to the previous one but uses a different set of external references. It is used when the program needs to access the mortgage loan information stored in the SAVE-COMM-AREA buffer.
7. A600-CALCULATE-MORTGAGE: This section performs the actual calculation of the monthly interest rate for the mortgage loan. It takes into account the interest rate, loan amount, and loan term to calculate the monthly payment amount. The result is then stored in the WS-FORMAT-NUMBER variable.
8. EXEC CICS LINK PROGRAM: This section executes theThe COBOL program above is designed to handle the mortgage loan processing, specifically for the monthly interest rate calculation. Here's a breakdown of the code:
1. Data Division: The first section declares various data items used throughout the program, such as flags, conversion tables, and external variable lengths.
2. Configuration Section: This section defines the environment variables for the program, including the source and object computer names, working storage size, and other configuration parameters.
3. Program ID: The program ID is declared here, along with the version number.
4. PROCEDURE DIVISION: The procedure division is where the actual program logic is contained. It consists of several sections:
a. Evaluate True/False: This section evaluates a series of conditions and branches to different sections based on the results. For example, it checks if the EIBCALEN (a condition code) is zero, and if so, it branches to the A100-PROCESS-MAP section.
b. Process Map: This section performs the actual mortgage loan processing. It reads the next record from the file, evaluates the record, and updates the appropriate fields in the OUTMAP structure. If any errors occur during the processing, the program branches to the A310-ERASE-MAP section to reset the map.
c. Send Map: This section sends the updated OUTMAP structure to the CICS server for further processing.
5. LINKAGE SECTION: The linkage section defines the external references used by the program, such as the EPSMLIST and EPSMTCOM libraries.
6. PROCEDURE DIVISION USING SAVE-COMM-AREA: This section is similar to the previous one but uses a different set of external references. It is used when the program needs to access the mortgage loan information stored in the SAVE-COMM-AREA buffer.
7. A600-CALCULATE-MORTGAGE: This section performs the actual calculation of the monthly interest rate for the mortgage loan. It takes into account the interest rate, loan amount, and loan term to calculate the monthly payment amount. The result is then stored in the WS-FORMAT-NUMBER variable.
8. EXEC CICS LINK PROGRAM: This section executes the

In [9]:
prompt_x=PromptTemplate(
            template=template_x,
            input_variables=["code_cobol"])
chain_x = LLMChain(llm=llm, prompt=prompt_x)
print(chain_x.run(cobolfirst))

Llama.generate: prefix-match hit


This is a COBOL program that calculates the sum of two numbers and displays the result. Here's an explanation of the code:

1. IDENTIFICATION DIVISION: This section defines the name of the program, its version number, and other information.
2. PROGRAM-ID: This specifies the name of the program. In this case, the program name is "SOMME".
3. DATA DIVISION: This section declares three variables: VAR-A, VAR-B, and SUM. The PIC ( Picture ) clause defines the data type of each variable. VAR-A and VAR-B are both integers with a field length of 5 digits, while SUM is an integer with a field length of 6 digits.
4. WORKING-STORAGE SECTION: This section defines the storage space for the program. The variables declared in the DATA DIVISION are stored here.
5. PROCEDURE DIVISION: This section contains the main logic of the program. It starts by moving the value 12345 to VAR-A and 54321 toThis is a COBOL program that calculates the sum of two numbers and displays the result. Here's an explanation of

Second : 2m16.8s --

First : This is a COBOL program that calculates the sum of two numbers and displays the result. Here's an explanation of the code:

* `IDENTIFICATION DIVISION`: This section defines the name of the program, its version number, and other information about the program.

* `PROGRAM-ID`: This specifies the unique identifier for the program. In this case, it is "SOMME".

* `DATA DIVISION`: This section declares variables that will be used in the program. In this case, we have two variables: `VAR-A` and `VAR-B`, both of which are picture clauses (PIC) with a field length of 5 digits. The `SUM` variable is also declared as a picture clause with a field length of 6 digits.

* `WORKING-STORAGE SECTION`: This section defines the working storage needed for the program. In this case, we only need to store three numbers: `VAR-A`, `VAR-B`, and `SUM`.

* `PROCEDURE DIVISION`: This section contains the actual program logic. Here's what happens in this section:

	+ We move the value 12345 to `VAR-A` and 54321 to `VAR-B`.

	+ We add `VAR-A` and `VAR-B` together using the `ADD` verb, and store the result in `SUM`.

	+ We display the value of `SUM` (i.e., the sum of 12345 and 54321) using the `DISPLAY` verb.

	+ Finally, we stop the program from running any further using the `STOP RUN` verb.

That's the basic structure of a COBOL program! Of course, there are many other features and capabilities of COBOL that we haven't touched on here, but this should give you a good starting point for understanding the basics of the language.This is a COBOL program that calculates the sum of two numbers and displays the result. Here's an explanation of the code:

* `IDENTIFICATION DIVISION`: This section defines the name of the program, its version number, and other information about the program.

* `PROGRAM-ID`: This specifies the unique identifier for the program. In this case, it is "SOMME".

* `DATA DIVISION`: This section declares variables that will be used in the program. In this case, we have two variables: `VAR-A` and `VAR-B`, both of which are picture clauses (PIC) with a field length of 5 digits. The `SUM` variable is also declared as a picture clause with a field length of 6 digits.

* `WORKING-STORAGE SECTION`: This section defines the working storage needed for the program. In this case, we only need to store three numbers: `VAR-A`, `VAR-B`, and `SUM`.

* `PROCEDURE DIVISION`: This section contains the actual program logic. Here's what happens in this section:

	+ We move the value 12345 to `VAR-A` and 54321 to `VAR-B`.

	+ We add `VAR-A` and `VAR-B` together using the `ADD` verb, and store the result in `SUM`.

	+ We display the value of `SUM` (i.e., the sum of 12345 and 54321) using the `DISPLAY` verb.

	+ Finally, we stop the program from running any further using the `STOP RUN` verb.

That's the basic structure of a COBOL program! Of course, there are many other features and capabilities of COBOL that we haven't touched on here, but this should give you a good starting point for understanding the basics of the language.


In [10]:
prompt_x=PromptTemplate(
            template=template_x,
            input_variables=["code_cobol"])
chain_x = LLMChain(llm=llm, prompt=prompt_x)
print(chain_x.run(code2))

Llama.generate: prefix-match hit


This is a COBOL program that allows you to manage the stock of products. Here's an explanation of what each part of the code does:

* IDENTIFICATION DIVISION: This section defines the name of the program, its version number, and other identifying information.

* PROGRAM-ID: This is a unique identifier for the program that can be used to reference it in other parts of the system.

* DATA DIVISION: This section declares the data items that will be used in the program. In this case, we have three data items:

+ PRODUIT: This item contains the code of the product (a 10-character field).

+ QUANTITE: This item contains the quantity of the product (a 5-digit field).

+ PRIX-UNITAIRE: This item contains the unit price of the product (a 6-digit field with a maximum value of 99.99).

* WORKING-STORAGE SECTION: This section defines the working storage that will be used in the program. In this case, we have four items:

+This is a COBOL program that allows you to manage the stock of products. Her

Second : 4m31.8s


First : This is a COBOL program that allows the user to input the code of a product, its quantity, and its unit price, and then calculates the total amount for the product. The program uses a series of display statements to prompt the user for input and to display the results of the calculation.

The program starts by defining four variables: PRODUIT, QUANTITE, PRIX-UNITAIRE, and MONTANT-TOTAL. These variables are used to store the code of the product, its quantity, its unit price, and the total amount for all products, respectively.

The program then enters a loop that prompts the user to input the code of a product, its quantity, and its unit price. The loop is controlled by the CHOIX-PRODUIT variable, which is set to 'N' at the beginning of the loop. If the user inputs 'O', the loop exits and the program displays the total amount for all products. If the user inputs 'N', the loop continues until the user inputs 'O'.

Inside the loop, the program uses a series of DISPLAY statements to prompt the user for input. The program also uses ACCEPT statements to accept the user's input and store it in the appropriate variable. The program then calculates the total amount for the product using the COMPUTE statement and stores the result in the MONTANT-TOTAL variable.

At the end of the loop, the program displays the total amount for all products and prompts the user to input 'O' or 'N' to indicate whether they want to continue or exit the program.

Overall, this program is a simple example of how to use COBOL to perform basic arithmetic operations and display output to the user.This is a COBOL program that allows the user to input the code of a product, its quantity, and its unit price, and then calculates the total amount for the product. The program uses a series of display statements to prompt the user for input and to display the results of the calculation.

The program starts by defining four variables: PRODUIT, QUANTITE, PRIX-UNITAIRE, and MONTANT-TOTAL. These variables are used to store the code of the product, its quantity, its unit price, and the total amount for all products, respectively.

The program then enters a loop that prompts the user to input the code of a product, its quantity, and its unit price. The loop is controlled by the CHOIX-PRODUIT variable, which is set to 'N' at the beginning of the loop. If the user inputs 'O', the loop exits and the program displays the total amount for all products. If the user inputs 'N', the loop continues until the user inputs 'O'.

Inside the loop, the program uses a series of DISPLAY statements to prompt the user for input. The program also uses ACCEPT statements to accept the user's input and store it in the appropriate variable. The program then calculates the total amount for the product using the COMPUTE statement and stores the result in the MONTANT-TOTAL variable.

At the end of the loop, the program displays the total amount for all products and prompts the user to input 'O' or 'N' to indicate whether they want to continue or exit the program.

Overall, this program is a simple example of how to use COBOL to perform basic arithmetic operations and display output to the user.

In [11]:
prompt_x=PromptTemplate(
            template=template_x,
            input_variables=["code_cobol"])
chain_x = LLMChain(llm=llm, prompt=prompt_x)
print(chain_x.run(code3))

Llama.generate: prefix-match hit


This is a simple COBOL program that takes an integer input (Number) and verifies if it matches a given value (123). If the input matches, the program displays "CORRECT" otherwise it displays "INCORRECT".
Here's a breakdown of the code:
* `IDENTIFICATION DIVISION`: This section defines the name of the program and other identifying information.
* `PROGRAM-ID`: This field specifies the unique identifier for the program.
* `DATA DIVISION`: This section declares the variables that will be used in the program. In this case, we have two variables:
	+ `NUMBER`: an integer variable that will hold the input value.
	+ `RESULT`: a character variable that will hold the output value.
* `WORKING-STORAGE SECTION`: This section defines the storage for the program's data and calculations. In this case, we have one working-storage area:
	+ `01 NUMBER PIC 9(3)`: This line declares a field called `NUMBER` that will hold an integer value with a maximum length of 3 digits.
	This is a simple COBOL program tha

Second : 2m7.5s --

First : This COBOL program has three divisions:

1. Identification Division: It contains the program name and the version number.
2. Data Division: It defines two variables, NUMBER and RESULT, which are used in the program.
3. Procedure Division: It is the main part of the program where the logic is written. Here we have a simple if-else statement that checks if the value of NUMBER is equal to 123. If it is, then the string 'CORRECT' is moved to RESULT, otherwise the string 'INCORRECT' is moved to RESULT. Finally, the result is displayed on the screen using the DISPLAY statement.
Note that in COBOL, variables are not defined with a semicolon like in other programming languages. Instead, they are defined using the PIC (Picture) clause, which specifies the data type and the length of the variable.This COBOL program has three divisions:

1. Identification Division: It contains the program name and the version number.
2. Data Division: It defines two variables, NUMBER and RESULT, which are used in the program.
3. Procedure Division: It is the main part of the program where the logic is written. Here we have a simple if-else statement that checks if the value of NUMBER is equal to 123. If it is, then the string 'CORRECT' is moved to RESULT, otherwise the string 'INCORRECT' is moved to RESULT. Finally, the result is displayed on the screen using the DISPLAY statement.
Note that in COBOL, variables are not defined with a semicolon like in other programming languages. Instead, they are defined using the PIC (Picture) clause, which specifies the data type and the length of the variable.

In [12]:
prompt_x=PromptTemplate(
            template=template_x,
            input_variables=["code_cobol"])
chain_x = LLMChain(llm=llm, prompt=prompt_x)
print(chain_x.run(code4))

Llama.generate: prefix-match hit


This is an example of COBOL program that demonstrates how to use CICS debug feature to convert date to integer. The program receives a date as input and converts it to an integer using the CICS debug feature. The program also demonstrates how to use the CICS debug feature to send data to the screen or file.
The program starts by defining the working storage section, which includes the variables needed for the program. It then defines the environment division, which includes the CICS debug feature parameters.
The program then receives the date as input and stores it in the W-CONVERSIONS variable. It then converts the date to an integer using the CICS debug feature by calling the EPSMLIST program. The EPSMLIST program is a CICS debug feature program that provides a list of all the fields in the current map, along with their lengths and types.
The program then checks if the conversion was successful or not using the RESPONSE variable. If the conversion was successful, it moves the integer

Second : 15m3.1s --

First : This code is a COBOL program that demonstrates how to use CICS (Customer Information Control System) for debugging purposes. It shows an example of a program that converts a date to an integer and then uses CICS to send a map (a collection of data) to a program called EPSMLIS, which is used to calculate mortgage payments.
The program starts by defining various variables and constants, such as the length of the comm area (W-COMAREA-LENGTH), the number of years in the mortgage (MORT-FILE-YEARS), and the rate of interest (MORT-FILE-RATE). It then moves on to the main program logic, which consists of three main sections:
1. The first section performs an evaluation of the comm area to determine if it is valid or not. If the comm area is invalid, it will show a screen and prompt the user to enter a valid comm area. If the comm area is valid, it will proceed to the next step.
2. The second section sends a map to the EPSMLIS program with the mortgage data. This includes the company name, phone number, and other relevant information. It then waits for the response from EPSMLIS and stores it in a variable called RESPONSE.
3. The third section calculates the mortgage payments using the return value from EPSMLIS. It then moves the data to an output area and updates the disp-count and end-of-file variables.
The program ends by performing some cleanup operations, such as closing the file and dealinglocating the comm area.

Overall, this code demonstrates how to use CICS for debugging purposes and how to interact with other programs (such as EPSMLIS) to perform complex calculations. It also highlights the use of COBOL syntax and programming constructs to create robust and maintainable software applications.This code is a COBOL program that demonstrates how to use CICS (Customer Information Control System) for debugging purposes. It shows an example of a program that converts a date to an integer and then uses CICS to send a map (a collection of data) to a program called EPSMLIS, which is used to calculate mortgage payments.
The program starts by defining various variables and constants, such as the length of the comm area (W-COMAREA-LENGTH), the number of years in the mortgage (MORT-FILE-YEARS), and the rate of interest (MORT-FILE-RATE). It then moves on to the main program logic, which consists of three main sections:
1. The first section performs an evaluation of the comm area to determine if it is valid or not. If the comm area is invalid, it will show a screen and prompt the user to enter a valid comm area. If the comm area is valid, it will proceed to the next step.
2. The second section sends a map to the EPSMLIS program with the mortgage data. This includes the company name, phone number, and other relevant information. It then waits for the response from EPSMLIS and stores it in a variable called RESPONSE.
3. The third section calculates the mortgage payments using the return value from EPSMLIS. It then moves the data to an output area and updates the disp-count and end-of-file variables.
The program ends by performing some cleanup operations, such as closing the file and dealinglocating the comm area.

Overall, this code demonstrates how to use CICS for debugging purposes and how to interact with other programs (such as EPSMLIS) to perform complex calculations. It also highlights the use of COBOL syntax and programming constructs to create robust and maintainable software applications.

In [13]:
formatted_prompt = prompt_x.format(code_cobol=code)
res = llm(prompt= formatted_prompt, llm= llm)
print(res)

Llama.generate: prefix-match hit


This program will receive a date and convert it to an integer in order to determine days from the current date. The program is written in COBOL and uses CICS as the transaction manager.
The program begins with a configuration section that defines the environment division, configuration section, source-computer, object-computer, data division, working storage section, and various variables.
The program then defines various segments such as EPSMLIST, W-RETIREMENT-WA, OUTMAP-REPEATE, EPSMORTF, and EPSNBRPM.
The program then moves to the procedure division, where it performs various tasks such as evaluating true or false conditions, performing a process based on the condition, and moving data between different areas.
The program uses CICS transactions to perform various tasks such as reading next from a file, sending maps, and erasing maps. The program also uses various COBOL statements such as MOVE, IF-THEN, and PERFORM to perform different operations.
The program ends with a linkage sect

Second : 14m37.5s -- 6mins? de mémoire pour first

First : This is an IBM COBOL program that demonstrates CICS/Debug functionality using EPSMLIST. It converts a date to an integer in a called program to determine days from the current date. The program is a work-like environment with data division, linkage section, procedure division, and program identification.  
The code includes various COBOL statements such as: 
* ID DIVISION - Defines the program name and identifier
* PROGRAM-ID - Specifies the program name and identifier for debugging purposes
* ENVIRONMENT DIVISION - Sets up the environment for the program, including the source and object computer addresses.
* CONFIGURATION SECTION - Configures the program's layout and formatting options.
* DATA DIVISION - Declares and defines various data items used throughout the program.
* WORKING-STORAGE SECTION - Allocates storage space for temporary variables and dynamic arrays.
* PROCEDURE DIVISION - Contains the main program logic, including calls to other programs and handling of errors.
* LINKAGE SECTION - Defines external references and links to other programs.
* EPSCMORT-MAINLINE - The main program entry point that handles key presses and calls other programs as needed.
* A100-PROCESS-MAP - Handles map-related operations, such as reading and writing files.
* A300-SEND-MAP - Sends map data to the CICS transaction manager.
* A310-ERASE-MAP - Erases any maps that have been sent to the CICS transaction manager.
* A600-CALCULATE-MORTGAGE - Calculates mortgage information based on input values and calls other programs as needed.
This program demonstrates the use of CICS/Debug functionality, including handling key presses, reading and writing files, and calling other programs. It also shows how to convert a date to an integer in a called program to determine days from the current date.This is an IBM COBOL program that demonstrates CICS/Debug functionality using EPSMLIST. It converts a date to an integer in a called program to determine days from the current date. The program is a work-like environment with data division, linkage section, procedure division, and program identification.  
The code includes various COBOL statements such as: 
* ID DIVISION - Defines the program name and identifier
* PROGRAM-ID - Specifies the program name and identifier for debugging purposes
* ENVIRONMENT DIVISION - Sets up the environment for the program, including the source and object computer addresses.
* CONFIGURATION SECTION - Configures the program's layout and formatting options.
* DATA DIVISION - Declares and defines various data items used throughout the program.
* WORKING-STORAGE SECTION - Allocates storage space for temporary variables and dynamic arrays.
* PROCEDURE DIVISION - Contains the main program logic, including calls to other programs and handling of errors.
* LINKAGE SECTION - Defines external references and links to other programs.
* EPSCMORT-MAINLINE - The main program entry point that handles key presses and calls other programs as needed.
* A100-PROCESS-MAP - Handles map-related operations, such as reading and writing files.
* A300-SEND-MAP - Sends map data to the CICS transaction manager.
* A310-ERASE-MAP - Erases any maps that have been sent to the CICS transaction manager.
* A600-CALCULATE-MORTGAGE - Calculates mortgage information based on input values and calls other programs as needed.
This program demonstrates the use of CICS/Debug functionality, including handling key presses, reading and writing files, and calling other programs. It also shows how to convert a date to an integer in a called program to determine days from the current date.

In [14]:
formatted_prompt = prompt_x.format(code_cobol=cobolfirst)
res = llm(prompt= formatted_prompt, llm= llm)
print(res)

Llama.generate: prefix-match hit


This is a COBOL program that calculates the sum of two numbers and displays the result. Here's a breakdown of the code:

* IDENTIFICATION DIVISION: This section defines the name of the program, its version, and other information.

* PROGRAM-ID: SOMME: This specifies the program identifier, which is a unique name for the program.

* DATA DIVISION: This section declares the variables used in the program. In this case, we have two variables: VAR-A and VAR-B, both of type PIC 9(5), meaning they can hold numbers up to five digits. The third variable, SUM, is also declared as a PIC 9(6) variable.

* WORKING-STORAGE SECTION: This section defines the storage for the variables declared in the DATA DIVISION. In this case, we have three working-storage sections, one for each variable.

* PROCEDURE DIVISION: This section contains the procedural code that performs the calculations and displays the results. Here's what happens:

1. The firstThis is a COBOL program that calculates the sum of two numb

Second : 2m6.6s --


First : This COBOL program has three divisions: Identification, Data, and Procedure. 

The Identification division begins with an "IDENTIFICATION DIVISION" statement, followed by the name of the program (SOMME). 
The Data division follows, beginning with a "DATA DIVISION". This division contains three variables: VAR-A, VAR-B, and SUM. Each variable is defined using the PIC ( Picture ) clause, which specifies the format and length of each variable. In this case, VAR-A and VAR-B are both fixed-length numeric fields with a length of 5 digits, while SUM is a fixed-length field with a length of 6 digits.
The Procedure division begins with a "PROCEDURE DIVISION". This division contains the logic for the program. In this case, the program adds two numbers (stored in VAR-A and VAR-B) and stores the result in SUM. The program then displays the result using the DISPLAY statement. Finally, the program ends with a "STOP RUN" statement.
The above code is written in COBOL programming language, which is primarily used for business applications, especially in finance and accounting systems. 
- Questions to answer:
1. What is the purpose of the program?
2. What are the three variables defined in the Data division, and what type of data do they contain?
3. How does the program add the values stored in VAR-A and VAR-B?
4. What is the result of the addition, and how is it stored?
5. How does the program display the result?This COBOL program has three divisions: Identification, Data, and Procedure. 

The Identification division begins with an "IDENTIFICATION DIVISION" statement, followed by the name of the program (SOMME). 
The Data division follows, beginning with a "DATA DIVISION". This division contains three variables: VAR-A, VAR-B, and SUM. Each variable is defined using the PIC ( Picture ) clause, which specifies the format and length of each variable. In this case, VAR-A and VAR-B are both fixed-length numeric fields with a length of 5 digits, while SUM is a fixed-length field with a length of 6 digits.
The Procedure division begins with a "PROCEDURE DIVISION". This division contains the logic for the program. In this case, the program adds two numbers (stored in VAR-A and VAR-B) and stores the result in SUM. The program then displays the result using the DISPLAY statement. Finally, the program ends with a "STOP RUN" statement.
The above code is written in COBOL programming language, which is primarily used for business applications, especially in finance and accounting systems. 
- Questions to answer:
1. What is the purpose of the program?
2. What are the three variables defined in the Data division, and what type of data do they contain?
3. How does the program add the values stored in VAR-A and VAR-B?
4. What is the result of the addition, and how is it stored?
5. How does the program display the result?

In [15]:
formatted_prompt = prompt_x.format(code_cobol=code2)
res = llm(prompt= formatted_prompt, llm= llm)
print(res)

Llama.generate: prefix-match hit


The COBOL program is designed to allow the user to enter information about a product, such as its code, quantity, and price. The program then calculates the total amount for the product and displays it to the user. The program also allows the user to choose whether they want to enter more products or end the program.

The program starts with an identification division that defines the program name, version number, and author.

The data division defines the fields that will be used to store the product information. The fields include:

* CODE-PRODUIT (10 characters) - the code for the product
* QUANTITE (5 digits) - the quantity of the product
* PRIX-UNITAIRE (6 digits, with a maximum value of 99) - the price of the product per unit
* MONTANT-TOTAL (8 digits, with a maximum value of 999) - the total amount for all products entered

The working storage section defines the areas where the data will be stored. The program uses the following working storage sections:

* PRODUIT - the produc

Second : 4m0.8s

First : This is a COBOL program that manages the inventory of products in a warehouse. It allows you to enter the code of a product, its quantity, and its unit price, and then calculates the total amount for that product. The program also asks if you want to enter another product or stop the program.
Here's a breakdown of the code:
* IDENTIFICATION DIVISION: This section defines the name of the program, its version number, and other information.
* PROGRAM-ID: This is the unique identifier for the program.
* DATA DIVISION: This section declares the variables that will be used in the program. In this case, we have three variables: PRODUIT (which stores the code of the product), QUANTITE (which stores the quantity of the product), and PRIX-UNITAIRE (which stores the unit price of the product).
* WORKING-STORAGE SECTION: This section declares the storage areas that will be used to store the data. In this case, we have one working storage area called MONTANT-TOTAL, which will store the total amount for all the products entered.
* PROCEDURE DIVISION: This section contains the procedures that make up the program. In this case, we have two procedures: UNE-FOIS and UNE-AUTRE-FOIS.
* UNE-FOIS: This procedure asks the user to enter the code of a product, its quantity, and its unit price. It then calculates the total amount for that product and displays it on the screen.
* UNE-AUTRE-FOIS: This procedure is similar to UNE-FOIS, but it also adds the total amount for the previous product to the current total amount, so that we can calculate the total amount for all the products entered.
* EXECUTIVE DIVISION: This section contains the main program loop, which is executed repeatedly until the user decides to stop the program. In this case, we have a single iteration of the loop, which executes the procedures UNE-FOIS and UNE-AUTRE-FOIS.
* DISPLAY statements: These statements are used to display messages on the screen. In this case, we have messages that ask the user to enter the code of a product, its quantity, and itsThis is a COBOL program that manages the inventory of products in a warehouse. It allows you to enter the code of a product, its quantity, and its unit price, and then calculates the total amount for that product. The program also asks if you want to enter another product or stop the program.
Here's a breakdown of the code:
* IDENTIFICATION DIVISION: This section defines the name of the program, its version number, and other information.
* PROGRAM-ID: This is the unique identifier for the program.
* DATA DIVISION: This section declares the variables that will be used in the program. In this case, we have three variables: PRODUIT (which stores the code of the product), QUANTITE (which stores the quantity of the product), and PRIX-UNITAIRE (which stores the unit price of the product).
* WORKING-STORAGE SECTION: This section declares the storage areas that will be used to store the data. In this case, we have one working storage area called MONTANT-TOTAL, which will store the total amount for all the products entered.
* PROCEDURE DIVISION: This section contains the procedures that make up the program. In this case, we have two procedures: UNE-FOIS and UNE-AUTRE-FOIS.
* UNE-FOIS: This procedure asks the user to enter the code of a product, its quantity, and its unit price. It then calculates the total amount for that product and displays it on the screen.
* UNE-AUTRE-FOIS: This procedure is similar to UNE-FOIS, but it also adds the total amount for the previous product to the current total amount, so that we can calculate the total amount for all the products entered.
* EXECUTIVE DIVISION: This section contains the main program loop, which is executed repeatedly until the user decides to stop the program. In this case, we have a single iteration of the loop, which executes the procedures UNE-FOIS and UNE-AUTRE-FOIS.
* DISPLAY statements: These statements are used to display messages on the screen. In this case, we have messages that ask the user to enter the code of a product, its quantity, and its

In [16]:
formatted_prompt = prompt_x.format(code_cobol=code3)
res = llm(prompt= formatted_prompt, llm= llm)
print(res)

Llama.generate: prefix-match hit


The COBOL program verifies whether the value entered by the user is equal to 123. If the value is equal, it displays "CORRECT" otherwise it displays "INCORRECT".

The code consists of three main parts:

1. Identification Division: This section defines the program name and its version.

2. Data Division: This section defines the variables used in the program. In this case, we have two variables: NUMBER and RESULT. The first one (NUMBER) is a picture clause of 9(3), meaning it can store numbers with up to three digits. The second one (RESULT) is a picture clause of X(6), meaning it can store strings with up to six characters.

3. Procedure Division: This section contains the logic of the program. We start by moving the value 123 to the NUMBER variable. Then, we check if the value is equal to 123 using an IF statement. If the value is equal, we move the string "CORRECT" to the RESULT variable and display it. Otherwise, we move the string "INCORRECT" to the RESULT variable and displayThe C

Second : 2m7.4s -- 

First : The above code is a simple COBOL program that takes an input (number) and checks if it is equal to 123, if it is then it displays "CORRECT" otherwise it displays "INCORRECT".
Here's a breakdown of the code:
* `IDENTIFICATION DIVISION`: This section defines the name of the program, its version, and other information.
* `PROGRAM-ID`: This is the unique identifier for the program.
* `DATA DIVISION`: This section declares the data items used in the program. In this case, we have two data items: `NUMBER` and `RESULT`. `NUMBER` is a pic 9(3) field, which means it can hold a three-digit number, and `RESULT` is a pic X(6) field, which means it can hold a six-character string.
* `WORKING-STORAGE SECTION`: This section defines the storage areas used by the program. In this case, we have one storage area called `NUMBER`.
* `01 NUMBER PIC 9(3)`: This line declares the `NUMBER` field as a pic 9(3) field.
* `01 RESULT PIC X(6)`: This line declares the `RESULT` field as a pic X(6) field.
* `PROCEDURE DIVISION`: This section contains the actual program logic. In this case, we have an if-then statement that checks if the value of `NUMBER` is equal to 123. If it is, then the program displays "CORRECT". Otherwise, it displays "INCORRECT".
* `MOVE 123 TO NUMBER`: This line moves the value 123 into the `NUMBER` field.
* `IF NUMBER = 123 THEN`: This line checks if the value of `NUMBER` is equal to 123. If it is, then the program executes the code inside the if statement.
* `MOVE 'CORRECT' TO RESULT`: This line moves the string "CORRECT" into the `RESULT` field.
* `ELSE`: This line is executed if the value of `NUMBER` is not equal to 123. In this case, it moves the stringThe above code is a simple COBOL program that takes an input (number) and checks if it is equal to 123, if it is then it displays "CORRECT" otherwise it displays "INCORRECT".
Here's a breakdown of the code:
* `IDENTIFICATION DIVISION`: This section defines the name of the program, its version, and other information.
* `PROGRAM-ID`: This is the unique identifier for the program.
* `DATA DIVISION`: This section declares the data items used in the program. In this case, we have two data items: `NUMBER` and `RESULT`. `NUMBER` is a pic 9(3) field, which means it can hold a three-digit number, and `RESULT` is a pic X(6) field, which means it can hold a six-character string.
* `WORKING-STORAGE SECTION`: This section defines the storage areas used by the program. In this case, we have one storage area called `NUMBER`.
* `01 NUMBER PIC 9(3)`: This line declares the `NUMBER` field as a pic 9(3) field.
* `01 RESULT PIC X(6)`: This line declares the `RESULT` field as a pic X(6) field.
* `PROCEDURE DIVISION`: This section contains the actual program logic. In this case, we have an if-then statement that checks if the value of `NUMBER` is equal to 123. If it is, then the program displays "CORRECT". Otherwise, it displays "INCORRECT".
* `MOVE 123 TO NUMBER`: This line moves the value 123 into the `NUMBER` field.
* `IF NUMBER = 123 THEN`: This line checks if the value of `NUMBER` is equal to 123. If it is, then the program executes the code inside the if statement.
* `MOVE 'CORRECT' TO RESULT`: This line moves the string "CORRECT" into the `RESULT` field.
* `ELSE`: This line is executed if the value of `NUMBER` is not equal to 123. In this case, it moves the string

In [17]:
formatted_prompt = prompt_x.format(code_cobol=code4)
res = llm(prompt= formatted_prompt, llm= llm)
print(res)

Llama.generate: prefix-match hit


This program converts a date to an integer using the EPSMLIS program, which calculates the number of years and months based on the input date. The program then uses the MORTGAGE-COMPANY-INFO file to retrieve mortgage information, such as the company name, phone number, and loan details. It then calculates the monthly payment amount based on the mortgage interest rate and loan details. Finally, it sends a map set to the EPSMLIS program with the calculated mortgage information.

- Error statements in the code

1. The first error statement is the use of "END-EXEC" without a corresponding "BEGIN-EXEC" statement. This can cause problems with the CICS runtime environment and should be avoided.
2. The second error statement is the use of "EVALUATE" without a corresponding "END-EVALUATE" statement. This can also cause problems with the CICS runtime environment and should be avoided.
3. The third error statement is the use of "MOVE" statements without proper validation of the input data. This c

Second : 14m35.6s

First Answer: This code is an example of a COBOL program that demonstrates how to use CICS/DEBUG functionality to debug a COBOL program. The program is written in a traditional COBOL style and includes various divisions, such as the ENVIRONMENT division, DATA division, and PROCEDURE division.
The program defines several variables and constants, such as W-FLAGS, W-CONVERSIONS, and RID-LENGTH, which are used throughout the program. It also includes a variety of procedures, such as A100-PROCESS-MAP, A300-SEND-MAP, and A310-ERASE-MAP, which perform specific tasks related to CICS/DEBUG.
The program demonstrates how to use CICS/DEBUG functionality by including several calls to the EPSMLIS program, which is a CICS/DEBUG program that provides various debugging functions. The program uses these functions to retrieve information about the current date and convert it to an integer value, as well as to send maps to and from CICS.
The program also includes several IF statements that check the status of the CICS/DEBUG sessions and perform different actions based on those statuses. For example, if the response from the EPSMLIS program is not normal, the program will display an error message and end the session. If the response is normal, the program will continue to process the map and display the results.
Overall, this code demonstrates how to use CICS/DEBUG functionality in a COBOL program to perform various tasks related to debugging and testing.This code is an example of a COBOL program that demonstrates how to use CICS/DEBUG functionality to debug a COBOL program. The program is written in a traditional COBOL style and includes various divisions, such as the ENVIRONMENT division, DATA division, and PROCEDURE division.
The program defines several variables and constants, such as W-FLAGS, W-CONVERSIONS, and RID-LENGTH, which are used throughout the program. It also includes a variety of procedures, such as A100-PROCESS-MAP, A300-SEND-MAP, and A310-ERASE-MAP, which perform specific tasks related to CICS/DEBUG.
The program demonstrates how to use CICS/DEBUG functionality by including several calls to the EPSMLIS program, which is a CICS/DEBUG program that provides various debugging functions. The program uses these functions to retrieve information about the current date and convert it to an integer value, as well as to send maps to and from CICS.
The program also includes several IF statements that check the status of the CICS/DEBUG sessions and perform different actions based on those statuses. For example, if the response from the EPSMLIS program is not normal, the program will display an error message and end the session. If the response is normal, the program will continue to process the map and display the results.
Overall, this code demonstrates how to use CICS/DEBUG functionality in a COBOL program to perform various tasks related to debugging and testing.

In [71]:
from langchain.llms import LlamaCpp
from langchain.chains import LLMChain
from langchain.prompts import PromptTemplate
from langchain.callbacks.manager import CallbackManager
from langchain.callbacks.streaming_stdout import StreamingStdOutCallbackHandler

callback_manager = CallbackManager([StreamingStdOutCallbackHandler()])
path=r"C:/Users/pc/OneDrive/Bureau/Ange'ECC files/DOCUMENTS/Mobilite/Cesure/GOUNADON_Ange-Marie/DeepBlock/IA_generative/.venv39/bin/llama-2-13b-chat.ggmlv3.q4_0.bin"



In [72]:
n_gpu_layers = 40  # Change this value based on your model and your GPU VRAM pool.
n_batch = 512  # Should be between 1 and n_ctx, consider the amount of VRAM in your GPU.

# Make sure the model path is correct for your system!
llm = LlamaCpp(
    model_path=path,
    n_gpu_layers=n_gpu_layers,
    n_batch=n_batch,
    callback_manager=callback_manager,
    verbose=True,
)

AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 | 


In [73]:
prompt = """
Question: A rap battle between Stephen Colbert and John Oliver
"""

In [75]:
llm(prompt)


Stephen Colbert and John Oliver, two of the most popular late-night TV hosts, are challenging each other to a rap battle. The battle will take place in front of a live studio audience, with each host performing original verses and battling each other with witty lyrics and clever wordplay.

The battle begins with Stephen Colbert taking the stage, wearing a sharp suit and a confident smirk. He launches into his first verse, laying down a barrage of tongue-in-cheek insults and clever jabs at John Oliver's expense.

John Oliver, dressed in a stylish blazer and sunglasses, takes the stage with a cool confidence. He fires back at Stephen with a series of witty one-liners and clever wordplay, leaving the audience in stitches.

The battle continues, with each host delivering increasingly impressive verses, each trying to outdo the other with their rap skills and humor. The audience is on the edge of their seats, cheering and laughing as the battle rages on.

In the end, it's a close call, but

"\nStephen Colbert and John Oliver, two of the most popular late-night TV hosts, are challenging each other to a rap battle. The battle will take place in front of a live studio audience, with each host performing original verses and battling each other with witty lyrics and clever wordplay.\n\nThe battle begins with Stephen Colbert taking the stage, wearing a sharp suit and a confident smirk. He launches into his first verse, laying down a barrage of tongue-in-cheek insults and clever jabs at John Oliver's expense.\n\nJohn Oliver, dressed in a stylish blazer and sunglasses, takes the stage with a cool confidence. He fires back at Stephen with a series of witty one-liners and clever wordplay, leaving the audience in stitches.\n\nThe battle continues, with each host delivering increasingly impressive verses, each trying to outdo the other with their rap skills and humor. The audience is on the edge of their seats, cheering and laughing as the battle rages on.\n\nIn the end, it's a close

In [79]:
template = """Question: {question}

Answer: Let's work this out in a step by step way to be sure we have the right answer."""

prompt = PromptTemplate(template=template, input_variables=["question"])

llm_chain = LLMChain(prompt=prompt, llm=llm)

question = "What NFL team won the Super Bowl in the year Justin Bieber was born?"

llm_chain.run(question)


Llama.generate: prefix-match hit




1. Justin Bieber was born on March 1, 1994.
2. The Super Bowl is typically played on the first Sunday of February.
3. Therefore, the Super Bowl that would have been played in the year Justin Bieber was born would have been Super Bowl XXXVIII (38).
4. Super Bowl XXXVIII was played on February 1, 2004.
5. So, the NFL team that won the Super Bowl in the year Justin Bieber was born was... the New England Patriots!

'\n\n1. Justin Bieber was born on March 1, 1994.\n2. The Super Bowl is typically played on the first Sunday of February.\n3. Therefore, the Super Bowl that would have been played in the year Justin Bieber was born would have been Super Bowl XXXVIII (38).\n4. Super Bowl XXXVIII was played on February 1, 2004.\n5. So, the NFL team that won the Super Bowl in the year Justin Bieber was born was... the New England Patriots!'